### ISSUE TITLE
Everything is regex

### ISSUE THREAD

**Issue by ryo33** [jsinger67/parol#19]
Thank you for the wonderful crate.

I personally don't like regex for lexer, and I didn't use it. However, `parol` seems to treat all strings as regex. I used regex for some grammar to try it out. This certainly seems to be useful. But most are not regex. Escaping everything is easy, but the grammar gets ugly.
I'm also concerned about the performance, but intuitively, this is probably not a problem.

I think one of the following would be better.
- Introduce regex literal like `Digits: /[\d]+/`
- Introduce pure string literal like `BlockBegin: '{'`

**Comment by jsinger67** [comment]
Hi ryo33,

this might actually be a good idea to improve user experience.
On the other hand, this means that `parol` has to escape non-regex terminals automatically.
I will have to think about it, but I think I will surely find a viable solution.

**Comment by jsinger67** [comment]
There is a regex::escape function that will do the job 😊
I will prepare a solution.

**Comment by jsinger67** [comment]
I decided to leave the current syntax (`"..."`) intact. It will behave like it was defined until now - so no need to update existing grammars. This means these strings are regarded as regular expressions and regex meta characters need to be escaped if they are not intended as part of a regular expression.

Then I will introduce two new syntaxes:
* `'..'`, i.e. single quoted string literals as literal or raw strings. `parol` will escape any regex meta character automatically - not used with regexes but with plain text
* `/../`, as regular expression strings, behaves exactly like the old double quoted string

I hope this fits your proposal.

**Comment by ryo33** [comment]
`parol` will be even more amazing!

**Comment by ryo33** [comment]
`String: "\u{0022}([^\\]|\\.)*\u{0022}";` can be `String: /"([^\\]|\\.)*"/`.

**Comment by jsinger67** [comment]
Fixed with 8e17689.
Have fun 🎉

**Comment by ryo33** [comment]
https://github.com/Hihaheho/Desk/blob/main/crates/systems/deskc-syntax-minimalist/src/grammar.par
What a beautiful grammar definition. Thanks a lot!
