### ISSUE TITLE
Installing with `cargo install` adds `serialize` and other tools directly to $PATH

### ISSUE THREAD

**Issue by Techcable** [jsinger67/parol#2]
Hi! I installed this with `cargo install,` but unfortunately this puts the additional tools like `serialize`, `first`, and `left_factor` directly in my `~/.cargo/bin`

This is unfortunate because although I want `parol` on my path, it is unintuitive to use a parol-specific command named `follow` or `serialize` (and it potentially conflicts with other tools).

Consider either:
1. Combining these tools into subcommands of the main `parol` executable. You would invoke `parol serialize` or `parol left-factor`.
2. Prefixing each individual command name: Have binaries named `parol-left-factor` and `parol-serialize`.

Option (1) has the advantage of reducing binary size :wink: Each individual executable is over 3MB for a combined total of 32.9 MB of additional tools 😮 . For comparison, the main `parol` binary is only 5MB. Because Rust has no stable ABI, it is incredibly dumb about sharing code.......

Option (2) is what cargo does for its extensions. Third-party extensions are named like `cargo-expand` or `cargo-bloat`.

If you want to go with (1) clap has excellent support for subcommands. That is what I recommend, but this option would require a little more work.

If you want to go with (2), then you can explicitly override the binary's `name` key in `Cargo.toml`. If you override this, then you also have to explicitly specify the `path` [see docs](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-name-field). This seems a little more clunky (and doesn't help with the binary sizes), but avoids having to mess with clap subcommands 😉

**Comment by Techcable** [comment]
I decided to implement option (1) in PR #3 

The tools aren't really proper subcommands, they're just shims hooked into clap (but its still cleaner than separate binaries)

**Comment by jsinger67** [comment]
Hi Techcable
thanks a lot for your elegant solution for a problem I wasn't even aware of.
I merged your pull request and ran `fmt` and `clippy` and then switched to version v0.5.1.
This version I published on crates.io right now.

I really appreciate your help!
