### ISSUE TITLE
How about once_cell instead of lazy_static

### ISSUE THREAD

**Issue by ryo33** [jsinger67/parol#20]
It provides `Lazy`, a non-macro version of lazy_static.

Here is the link: https://github.com/matklad/once_cell
It says:
> The API of once_cell is being proposed for inclusion in [std](https://github.com/rust-lang/rfcs/pull/2788).

Also, here is the tracking issue of it: https://github.com/rust-lang/rust/issues/74465

This is a matter of preference, but I favor `once_cell`.

**Comment by jsinger67** [comment]
@ryo33 
Thank you for the hint. :blush:
Yes, I can consider using once_cell instead of lazy_static.

**Comment by ryo33** [comment]
May I start working on a pull-req for this?

**Comment by jsinger67** [comment]
Yes of course. I'm currently working on a solution for #28 which will take some considerable amount of time.
I can only work on this project in my spare time so any help is really appreciated. ☺️
