### ISSUE TITLE
How about cargo workspace

### ISSUE THREAD

**Issue by ryo33** [jsinger67/parol#21]
Currently, each parol-related crate seems to have its own GitHub repository. We can use [cargo workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) to make them into one repository.
As a user, I think the workspace style is easier to refer to the code. Best of all, it eliminates the need for multiple git clones.
Also, monorepo would be more advantageous in terms of maintenance.

Many of the libraries I'm following seem to use the workspace style:
- [Bevy](https://github.com/bevyengine/bevy)
- [Rapier](https://github.com/dimforge/rapier)

**Comment by jsinger67** [comment]
Hi Ryo,

good point :blush:
I could imagine to put parole, parol_runtime, parol-macros und perhaps even parol-ls and parol-vscode in one workspace into one git repository.

**Comment by ryo33** [comment]
Yes, that seems nice! There will be no need to separate a single pull-req across multiple crates, crate by crate.

**Comment by ryo33** [comment]
@jsinger67 May I create a pull-req for this? I intend to merge the git histories of all repositories.

**Comment by jsinger67** [comment]
Yes of course. 👍
You're amazingly fast 😉
