### ISSUE TITLE
Matching with the end of input

### ISSUE THREAD

**Issue by dalance** [jsinger67/parol#230]
I'm tring to write a language which separated by linebreak like below:

```
%start Lang
%title "Lang grammar"
%comment "Empty grammar generated by `parol`"
%line_comment "//"
%auto_newline_off

%%

Lang: { "Hello world!" LineBreak };
LineBreak: /(\n|\r|\r\n|$)/;
```

I expect the `LineBreak` will be matched with the end of input.
But I tried the following text which doesn't have the trailing linebreak, and I got an error:

```
$ cat test.txt
Hello world!
$ hexdump test.txt
0000000 6548 6c6c 206f 6f77 6c72 2164
000000c
$ cargo run --bin lang -- ./test.txt
   Compiling lang v0.1.0 (/home/hatta/work/repos/playground/lang)
    Finished dev [unoptimized + debuginfo] target(s) in 1.29s
     Running `target/debug/lang ./test.txt`
Error: Failed parsing file ./test.txt

Caused by:
    Found "'$'(EndOfInput) at :0:0-0:0"
    Current scanner is INITIAL
    Current production is:
    /* 3 */ LineBreak: "LineBreak";
    Expecting one of LineBreak
```

Is there any way to match with the end of input?

**Comment by jsinger67** [comment]
Hi @dalance,
Good point.
Parol handles EOI tokens implicitly.
This means that the grammar knows when the end of input is valid.
In your case this means that you have to solve this merely by the means of the grammar. More precisely, simply make the last line end optional and all will settle down in the right place.

**Comment by jsinger67** [comment]
This should do the job:
```
%start Lang
%title "Lang grammar"
%comment "Empty grammar generated by `parol`"
%line_comment "//"
%auto_newline_off

%%

Lang: [ Items ] [LineBreak];
Items: Hello { LineBreak Hello };
Hello: "Hello world!";
LineBreak: /(?s)(\n|\r|\r\n)/;
```

**Comment by dalance** [comment]
Thank you for your suggestion.
It works fine.
