### ISSUE TITLE
Smarter type generation in auto generation - Part 1 Deduce the variant name from its right-hand side.

### ISSUE THREAD

**Issue by ryo33** [jsinger67/parol#28]
I've tried `parol` with auto-generation and am very pleased with its functionality, and it meets most requirements for creating my Desk-lang parser.
I'd like to suggest some trivial improvements to auto-generation in this issue.

## Current behavior

Given expanded grammar:
```
Expr: Comment Expr;
Expr: Let;
Comment: ...
Let: ...
```

Now, `parol` generates something like this:

```rust
enum Expr {
    Expr0(Expr0),
    Expr1(Expr1),
}

struct Expr0 {
    pub comment: Box<Comment>,
    pub expr: Box<Expr>,
}

struct Expr1 {
    pub r#let: Box<Let>,
}

struct Comment { ... }
struct Let { ... }
```

## Suggested behavior

I'd like to suggest these ~~two~~three.
1. Deduce the variant name from its right-hand side.
2. Omit struct generation for a variant if its right-hand side is a single item.
3. Use `Box` as little as possible, like:
    1. At the moment when recursion occurs.
    2. If the type size is large. (We may don't need this behavior, and it would be a too-early optimization)

So the generated code for the above example will be like this:

```rust
enum Expr {
    CommentExpr(CommentExpr),
    Let(Let),
}

// Former Expr0
struct CommentExpr {
    pub comment: Comment,
    pub expr: Box<Expr>,
}

// Expr1 is not generated

struct Comment { ... } 
struct Let { ... }
```

**Comment by jsinger67** [comment]
@ryo33 
Great suggestions!
I was never really satisfied with the current way to deduce the variant names of an Enum. The only thing that I wanted was, that they should be as stable as possible when the user changes his grammar description. This is also guaranteed by your proposal with the benefit of gaining more readability.
Also, the second proposal is useful, and I will try to find a solution for it.
The third one may involve some deeper analyses but is really worth to strive for.

**Comment by jsinger67** [comment]
@ryo33 
I have a partly solution here c8140d4 on branch enhancement/smart-type-generation
(1. Deduce the variant name from its right-hand side.)

If you have time, I would like you to have a look at it.

I decided to deviate from the original proposal in a single part.
Because the struct types for all productions and all non-terminals share the same namespace the result was not always better readable.
So, the names of production types are built by a concatenation of non-terminal (LHS) and the right-hand side (RHS) which you suggested.

```rust
enum Expr {
    CommentExpr(ExprCommentExpr),
    Let(ExprLet),
}

struct ExprCommentExpr { ... }
struct ExprLet { ... }
```

If I hadn't done this, I would regularly end up with results like this:

```rust
enum Expr {
    CommentExpr(CommentExpr),
    Let(Let0),
}

// Type derived for production x
// Expr: Let;
struct Let0 { ... }

// Type derived for non-terminal Let
struct Let { ... }
```

The first variant produces a bit more clutter and the second is disambiguated by adding numbers to the type names.
I would also be interested in your opinion about this decision. It would be easy to change this decision.

Thanks in advance
Jörg

**Comment by ryo33** [comment]
@jsinger67 
Prefixing production types with LHS seems nice. I came up with the following example:

```
Expr: Variable
    | ...
    ;
Type: Variable
    | ...
    ;
```
It generates:
```rust
 enum Expr {
    Variable(ExprVariable),
    ...
}
struct ExprVariable {...}
enum Type {
    Variable(TypeVariable),
    ...
}
struct TypeVariable {...}
```

**Comment by jsinger67** [comment]
I would like to split this issue into three separate ones.

1. Deduce the variant name from its right-hand side.
2. Omit struct generation for a variant if its right-hand side is a single item.
3. Use `Box` as little as possible, like:
    1. At the moment when recursion occurs.
    2. If the type size is large. (We may don't need this behavior, and it would be a too-early optimization)

**Comment by jsinger67** [comment]
I added two new issues:
#37 and #38

**Comment by jsinger67** [comment]
Closed with c8140d4

**Comment by ryo33** [comment]
This feature has created a wonderful, inspiring experience. Thanks a lot!

**Comment by jsinger67** [comment]
I'm happy to improve the overall usability.
And it' was your proposal and I owe you that ☺️
Part 2 is on a good way in the meantime 💪
