### ISSUE TITLE
[parol new] Generate .gitignore to ignore generated files (opt-in or opt-out)

### ISSUE THREAD

**Issue by ryo33** [jsinger67/parol#32]
I think that in most use-case:
1. users want to put generated files in `src` for easy reference and better IDE support.
2. users don't want to maintain the generated files under git control not to include derived differences in the history.

1 has already been achieved.
About 2, some users may be surprised that git is going to track the generated files.

I believe an opt-out behavior like `parol new --track-generated-files` would be preferred.

After hearing other opinions, I'll create a pull-req for this.

**Comment by jsinger67** [comment]
Yeah, this is a really good point and can improve the usability of `parole new`. The pull request is welcome ☺️
