### ISSUE TITLE
Raw string literal

### ISSUE THREAD

**Issue by dalance** [jsinger67/parol#321]
I want to add raw string literal support like Rust or C#.

```
// Rust style
r##"..."##

// C# style
"""..."""
```

In this case, the count of delimiter (`#` or `"`) will be adjusted to the contents.
So I think this pattern can't be written by regex without backreference.

Do you have any idea to implement this feature?

**Comment by jsinger67** [comment]
You can't ensure that start and end delimiters have the same counts with regexes alone because this is no regular language anymore.
Best way would be you check this in the grammar processing.

**Comment by dalance** [comment]
Thank you for your suggestion.
I'll try it.
