### ISSUE TITLE
Specifing a name for type generation without assigning a user type

### ISSUE THREAD

**Issue by ryo33** [jsinger67/parol#35]
We can assign a user type in PAR grammar, but we seem unable to specify a name for type generation.
I think it's nice to make the semantics of `: name` togglable between:
- A user type
- A name for type generation

## Example usage
```
LongRegex: /very long regex/: ANiceName
```
generates:
```rust
struct LongRegex {
    a_nice_name: Token
}
```

**Comment by jsinger67** [comment]
There still exists a solution for your problem.
```
ANiceName: /very long regex/;
```
But this might be not universal enough because it only works for terminals.

What do you think, would the existing way be sufficient or do we need a more general solution?

**Comment by ryo33** [comment]
Oh, that's nice.
For my use case, it's sufficient.
