### ISSUE TITLE
Bart

### ISSUE THREAD

**Issue by ryo33** [jsinger67/parol#46]
I have a solution to fix this situation, and I will sent a pull request today.

**Comment by ryo33** [comment]
I’ll try tomorrow.

**Comment by ryo33** [comment]
I’m going to create a really tiny library for generating Rust codes.

**Comment by ryo33** [comment]
https://github.com/ryo33/ume
I finally finished it. The code is about three times longer than I first thought, but it works nicely with zero dependencies.
Despite its simplicity, it can do much. Here is an example code.

```rust
let use_something = ume!(use something::prelude::*;);
let let_one = ume!(let one = 1;);
let let_two = ume!(let two = 2;);
let code = ume! {
    #use_something
    fn main() {
        #let_one
        #let_two
        println!("{one} {two}");
    }
};
```

Then, codes will be manually generated by Rust code without using template files. It will be less declarative, but the code generation will be easily understood by anyone who can read Rust, and it will only depend on 60 lines of macros.

I will create a draft pull-req that uses it partially. If I get a positive response, I will replace others in it.

On a side note, I am unhappy with the name `ume`. It means "plum" and "embed" in Japanese. If anyone has any other good ideas, please let me know.

**Comment by jsinger67** [comment]
I'm really impresed! 💪
I find the idea using tokenstream processing really promissing.
Please, take the extra time you need to get it in a good shape. No need to hurry currently.
Good luck!
