### ISSUE TITLE
Bizzare error running scanner_states

### ISSUE THREAD

**Issue by Techcable** [jsinger67/parol#5]
The Scanner States example encounters a bizarre error on the latest commit (8c608d9b00f605c55df5eb20ab13ec6868cf3213):

A similar error seems to have existed in versions 0.4.0, 0.3.0, and 0.2.0. I cannot trace it back any further due to the lack of `parol-runtime` for 0.1.0. Is this intended?

Command: `pwsh build_parsers.ps1` then `pwsh run_parsers.ps1`
````
Running Scanner States example...
Error: parol_runtime::parser::syntax_error

  × Failed parsing file ./examples/scanner_states/scanner_states_test.txt
  ├─▶ Production prediction failed at state 0
  ╰─▶ LA(1): '\\'(Error) at "./examples/scanner_states/scanner_states_test.txt":4:23.
      at non-terminal "StringContent"
      Current scanner is String
      Current production is:
      /* 5 */ StringContent: StringElement StringContent;
      Expecting one of "Escaped", "EscapedLineEnd", "NoneQuote", "StringDelimiter"
  help: Syntax error in input prevents prediction of next production

Error: parol_runtime::unexpected_token

  × Unexpected token: LA(1) (Error)
   ╭─[./examples/scanner_states/scanner_states_test.txt:3:1]
 3 │ Id2
 4 │ "2. \"String\t\" with \
   ·                       ┬
   ·                       ╰── Unexpected token
 5 │ escaped newline"
   ╰────
  help: Unexpected token
````

You might want to document it if this is an intended error...

**Comment by jsinger67** [comment]
I can't confirm your problem on (8c608d9b00f605c55df5eb20ab13ec6868cf3213).
Tried it on Window where I usually develop (1.57.0, stable-x86_64-pc-windows-msvc) and a docker image base on Ubuntu (1.57.0-x86_64-unknown-linux-gnu).
No problems in both of them.

**Comment by jsinger67** [comment]
I guess it is a MacOS specific issue.
Can you please confirm if changing the example like follows helps?
`examples/scanner_states/scanner_states-exp.par`, line 23

/* 12 */ EscapedLineEnd: <String>"\u{5c}[\s*](\r?\n|\r)";

**Comment by jsinger67** [comment]
Fixed by Techcable. Thanks a lot!
