### ISSUE TITLE
Is parol production ready ?

### ISSUE THREAD

**Issue by Megamac** [jsinger67/parol#509]
In the parol documentation is stated, that parol is not yet production ready.  @jsinger67 : is this still your opinion ?

**Comment by jsinger67** [comment]
@Megamac,
version 1 of parol is stable and production ready with all the usual disclaimers. You should use the latest releases available on crates.io with version >=1.
Version 2 is still in its Beta phase.
Thank you for pointing me at the documentation, e.g. README, where this fact is not clearly pointed out. I will update all the relevant documents soon.

**Comment by Megamac** [comment]
That's great, thanks for the clarification 👍
