### ISSUE TITLE
What is `trim_parse_tree`?

### ISSUE THREAD

**Issue by dalance** [jsinger67/parol#59]
I tried to use `trim_parse_tree` at parol 0.18.1, and got about 20-30% performance gain.

```
throughput/parse        time:   [26.970 ms 26.976 ms 26.984 ms]
                        thrpt:  [562.98 KiB/s 563.15 KiB/s 563.27 KiB/s]
                 change:
                        time:   [-22.763% -21.446% -20.414%] (p = 0.00 < 0.05)
                        thrpt:  [+25.651% +27.300% +29.472%]
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  6 (6.00%) high mild
  2 (2.00%) high severe
```

I want to know the actual effect of `trim_parse_tree`.
The doc says that it is useful when the whole parse tree is not needed.

> Doing so the parse tree doesn’t grow much and runtime overhead is diminished. Useful when enabling production mode and the whole parse tree is not needed.

In my understanding, my usage requires the whole parse tree.
So I thought that `trim_parse_tree` can't be used, but `trim_parse_tree` didn't break any my testcases actually.
What information is trimmed?

**Comment by jsinger67** [comment]
Hi @dalance,
the parser tree is the structure returned by the parser method.
It resembles the concrete structure of the pars

**Comment by dalance** [comment]
Thank you for your description.
I understood that `trim_parse_tree` can be used in my usage.
