### ISSUE TITLE
Performance of id_tree

### ISSUE THREAD

**Issue by dalance** [jsinger67/parol#60]
I investigated the performance of id_tree.
In the flamegraph, many time is consumed by `PartialEq` of `ProcessUniqueId`.

The `ProcessUniqueId` which is provided by https://github.com/Stebalien/snowflake is 128bit.
So I thought another snowflake implementation which provides 64bit id may get performance gain.

I got about 20% performance gain with the custom id_tree which uses https://github.com/BobAnkh/idgenerator.

https://github.com/dalance/id-tree/tree/use_idgenerator

```
throughput/parse        time:   [22.283 ms 22.315 ms 22.372 ms]
                        thrpt:  [679.05 KiB/s 680.77 KiB/s 681.75 KiB/s]
                 change:
                        time:   [-18.014% -17.837% -17.606%] (p = 0.00 < 0.05)
                        thrpt:  [+21.369% +21.710% +21.973%]
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  5 (5.00%) high mild
  3 (3.00%) high severe
```

**Comment by udoprog** [comment]
I don't see an immediate reason why that shouldn't be possible.

A major difference I've done in 0.14.* which I just recently released though was the ability to have differently sized span indexes and pointer sizes ([default being `u32` and `usize` like before](https://github.com/udoprog/syntree/blob/main/src/builder.rs#L73)). This makes the API a bit harder to use if you're referencing identifiers which it seems like `id_tree_layout` will want to do.

Instead of this:

```rust
let id: syntree::Id = tree.first().ok_or("missing")?.id();
```

You'll have to do this (if you're using `usize` pointers):

```rust
use syntree::pointer::Width;

let id: <usize as Width>::Pointer = tree.first().ok_or("missing")?.id();
```

Of course the intent is that `usize` could be generic which would make it `W::Pointer` but that's up to you.

Good luck!

**Comment by jsinger67** [comment]
@udoprog 
Thanks a lot for your explanation!
I hope I can start with this soon 😃

**Comment by jsinger67** [comment]
@udoprog 
I have one question.
Is it possible to not include skipped tokens into the tree, i.e., to have a non-contiguous span information?
As far as I understand the API, it is not.

The API for token insertion (`Builder::token`) simply accepts a length information which is internally expanded to a span.

I think it is not necessary for `parol`'s use cases, I only need a working tree implementation. The nodes I insert contain the information if they are tokens or non-terminals.
**So, there's no need for action here.**

But if I wanted to use `print_with_source` this won't work out of the box.

I could imagine that having non-contiguous span information in the tree's leaves is a possible use case for other users.
Maybe a method where besides the length of the token a gap size (length of skipped text) can be provided.

As I said before there is no need from my side here. I just stumbled about that.

By the way, `syntree_layout` crate is on its way. 👍

**Comment by udoprog** [comment]
Hm, yeah. It's intended as a non-destructive representation of a syntax tree, which implies a contiguous set of spans from *something* being processed.

Additional information can be carried in the tree though, as is the case with the [synthetic strings example](https://github.com/udoprog/syntree/blob/main/examples/synthetic_strings.rs), but you'd have to implement that in your own `print_with_source` implementation.

**Comment by jsinger67** [comment]
The first step has been taken:
[syntree_layout](https://github.com/jsinger67/syntree_layout)
😎

**Comment by jsinger67** [comment]
@dalance 
I have for working version on branch `syntree`.
I would appreciate if you could do some performance evaluations there.
Thanks in advance!

**Comment by jsinger67** [comment]
In my scenario I counted 5.695.873 elements in this parse tree

**Comment by dalance** [comment]
I tried `syntree` branch.
I got 2.3x performance gain. It's awesome!!!

```
throughput/parse        time:   [11.867 ms 11.875 ms 11.885 ms]
                        thrpt:  [1.2612 MiB/s 1.2623 MiB/s 1.2632 MiB/s]
                 change:
                        time:   [-56.856% -56.801% -56.754%] (p = 0.00 < 0.05)
                        thrpt:  [+131.24% +131.49% +131.78%]
                        Performance has improved.
Found 20 outliers among 100 measurements (20.00%)
  9 (9.00%) low mild
  3 (3.00%) high mild
  8 (8.00%) high severe
```

**Comment by jsinger67** [comment]
Great, thanks!! 👍

**Comment by jsinger67** [comment]
As of version `parol 0.19.0` and `parol_runtime 0.15.0` we have switched to `syntree` crate as parse tree implemenation.
It was a huge amount of changes. Regarding this all went relatively smooth.
Thanks to all contributors!! 🥇

**Comment by udoprog** [comment]
Very cool!

Also, if you don't want to store spans in the tree (which might save you some memory since you're not using them), consider using [`Empty` instead of `u32`](https://docs.rs/syntree/latest/syntree/struct.Builder.html#method.new_with).

**Comment by jsinger67** [comment]
Ok, good hint. I wasn't sure if I will ever need any span information. But as it turned out I won't.
So, I will probably use Empty in the next version.
